version: '3'
services:
  collector-microsoft-intune:
    image: openaev/collector-microsoft-intune:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL}
      - COLLECTOR_MICROSOFT_INTUNE_TENANT_ID=${MICROSOFT_INTUNE_TENANT_ID}
      - COLLECTOR_MICROSOFT_INTUNE_CLIENT_ID=${MICROSOFT_INTUNE_CLIENT_ID}
      - COLLECTOR_MICROSOFT_INTUNE_CLIENT_SECRET=${MICROSOFT_INTUNE_CLIENT_SECRET}
      - COLLECTOR_MICROSOFT_INTUNE_DEVICE_FILTER=${MICROSOFT_INTUNE_DEVICE_FILTER}
      - COLLECTOR_MICROSOFT_INTUNE_DEVICE_GROUPS=${MICROSOFT_INTUNE_DEVICE_GROUPS}
    restart: always
