version: '3'
services:
  collector-aws-resources:
    image: openaev/collector-aws-resources:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL}
      - COLLECTOR_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - COLLECTOR_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COLLECTOR_AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - COLLECTOR_AWS_ASSUME_ROLE_ARN=${AWS_ASSUME_ROLE_ARN}
      - COLLECTOR_AWS_REGIONS=${AWS_REGIONS}
    restart: always
