services:
  collector-google-workspace:
    image: openaev/collector-google-workspace:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"Google Workspace"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-PT1H}
      - COLLECTOR_GOOGLE_WORKSPACE_SERVICE_ACCOUNT_JSON=${GOOGLE_WORKSPACE_SERVICE_ACCOUNT_JSON}
      - COLLECTOR_GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL=${GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL}
      - COLLECTOR_GOOGLE_WORKSPACE_CUSTOMER_ID=${GOOGLE_WORKSPACE_CUSTOMER_ID:-my_customer}
      - COLLECTOR_INCLUDE_SUSPENDED=${INCLUDE_SUSPENDED:-false}
      - COLLECTOR_SYNC_ALL_USERS=${SYNC_ALL_USERS:-false}
    restart: unless-stopped
