version: '3'
services:
  collector-microsoft-azure:
    image: openaev/collector-microsoft-azure:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-PT1H}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL}
      - COLLECTOR_MICROSOFT_AZURE_TENANT_ID=${MICROSOFT_AZURE_TENANT_ID}
      - COLLECTOR_MICROSOFT_AZURE_CLIENT_ID=${MICROSOFT_AZURE_CLIENT_ID}
      - COLLECTOR_MICROSOFT_AZURE_CLIENT_SECRET=${MICROSOFT_AZURE_CLIENT_SECRET}
      - COLLECTOR_MICROSOFT_AZURE_SUBSCRIPTION_ID=${MICROSOFT_AZURE_SUBSCRIPTION_ID}
      - COLLECTOR_MICROSOFT_AZURE_RESOURCE_GROUPS=${MICROSOFT_AZURE_RESOURCE_GROUPS}
    restart: always
