services:
  collector-mitre-attack:
    image: openaev/collector-mitre-attack:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"MITRE ATT&CK"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-P7D}
    restart: unless-stopped
