services:
  collector-atomic-red-team:
    image: openaev/collector-atomic-red-team:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"Atomic Red Team"}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-P7D}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
    restart: unless-stopped
